### PR TITLE
Fix custom capability creation broken by non-array hidden_caps

### PR DESCRIPTION
**Pull request by cartpauj**
## Problem

Reported on the WordPress.org support forum: [Unable to create custom capabilities in v3.2.22](https://wordpress.org/support/topic/unable-to-create-custom-capabilities-in-v3-2-22/)

In v3.2.22, editing a role and typing into the new-capability field throws a JS error and the **Add New** button never enables, so custom caps can't be created (works in v3.2.19):

```
Uncaught TypeError: members_i18n.hidden_caps.includes is not a function
    at HTMLInputElement.<anonymous> (edit-role.js:697)
```

## Root cause

`members_get_hidden_caps()` returned `array_unique( $caps )`. `array_unique` **preserves the original integer keys**, so when duplicate caps occur — e.g. `edit_files`/`edit_plugins`/`edit_themes` are added in both the "File editing" and "File mods" blocks on sites with `DISALLOW_FILE_EDIT` / `DISALLOW_FILE_MODS` defined — the keys become non-sequential (gaps).

`wp_localize_script` JSON-encodes a PHP array with non-sequential keys as a JS **object** (`{}`) rather than an **array** (`[]`). Objects have no `.includes()`, hence the `TypeError`. The `.includes()` check was introduced after v3.2.19, which is why older versions weren't affected.

## Fix

- **`inc/functions-capabilities.php`** — wrap the return in `array_values()` to reindex, guaranteeing the localized value is always a JS array. (root-cause fix)
- **`js/edit-role.js`** (+ rebuilt `edit-role.min.js`) — defensive guard coercing `members_i18n.hidden_caps` to an array, so a third-party `members_remove_hidden_caps` filter returning an odd shape can't reintroduce the crash.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Review by omaraelhawary — APPROVED** [review]
@cartpauj Thanks for fixing that 👍
